version: "3"
services:
    rabbitmq:
        hostname: rabbitmq-server
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        hostname: redis-server
        image: redis:latest
        ports:
            - "6379:6379"

    web_frontend:
        build: .
        command: gunicorn -b 0.0.0.0:5555 -w 4 --reload wsgi:app
        environment:
            PYTHONUNBUFFERED: "true"
        ports:
            - "5580:5580"
        links:
            - rabbitmq
            - redis
        healthcheck:
            test: "curl -f http://0.0.0.0:5555/index || false"
            interval: 60s
            timeout: 10s
            retries: 3
    
    celery_beat:
        build:
            context: .
            dockerfile: Dockerfile_celerybeat
        command: celery -A celery_worker:celery beat -l DEBUG
        volumes:
            - .:/app
        links:
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq
            - redis
    
    celery_worker_1:
        build:
            context: .
            dockerfile: Dockerfile_celery_worker_1
        command: celery -A celery_worker:celery worker -l DEBUG -n worker@%h -Q locations -c 2
        volumes:
            - .:/app
        links:
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq
            - redis
    
    celery_worker_2:
        build:
            context: .
            dockerfile: Dockerfile_celery_worker_2
        command: celery -A celery_worker:celery worker -l DEBUG -n worker@%h -Q devices -c 2
        volumes:
            - .:/app
        links:
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq
            - redis
    
    celery_worker_3:
        build:
            context: .
            dockerfile: Dockerfile_celery_worker_3
        command: celery -A celery_worker:celery worker -l DEBUG -n worker@%h -Q endpoints -c 2
        volumes:
            - .:/app
        links:
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq
            - redis

    flower:
        build:
            context: .
            dockerfile: Dockerfile_flower
        environment:
            - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
            - CELERY_RESULT_BACKEND=redis://redis:6379/0        
        command: flower -A celery_worker:celery --address=0.0.0.0 --port=5000
        volumes:
          - .:/app
        ports:
          - "5000:5000"
        links:
          - database
          - rabbitmq
        healthcheck:
            test: "curl -f http://0.0.0.0:5000 || false"
            interval: 60s
            timeout: 10s
            retries: 3

    database:
        hostname: mongodb-server
        image: mongo:latest
        ports:
            - "27017:27107"
    
    mysql:
        hostname: mysql-server
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=netauto
            - MYSQL_DATABASE=netauto
        ports:
            - "3306:3306"
